fileinfo.lo: /var/www/virtual/rusimport.com/Fileinfo-1.0.4/fileinfo.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/virtual/rusimport.com/Fileinfo-1.0.4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/virtual/rusimport.com/Fileinfo-1.0.4/fileinfo.c -o fileinfo.lo 
$(phplibdir)/fileinfo.la: ./fileinfo.la
	$(LIBTOOL) --mode=install cp ./fileinfo.la $(phplibdir)

./fileinfo.la: $(shared_objects_fileinfo) $(FILEINFO_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_fileinfo) $(FILEINFO_SHARED_LIBADD)

